version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: rrhh-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - rrhh-network

  nginx:
    image: nginx:alpine
    container_name: rrhh-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - rrhh-network

  mysql:
    image: mysql:8.0
    container_name: rrhh-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_USER: ${DB_USERNAME:-laravel}
    ports:
      - "33061:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - rrhh-network

  redis:
    image: redis:alpine
    container_name: rrhh-redis
    restart: unless-stopped
    ports:
      - "63791:6379"
    networks:
      - rrhh-network

networks:
  rrhh-network:
    driver: bridge

volumes:
  mysql_data:
